name: test  # default testing environment name from conda-incubator
dependencies:
  - python=3.8
  - pip
  - cmake
  - gsl
  - swig
  - pyyaml
  - numpy
  - scipy
  - camb
  - fast-pt
  - pytest
  - pytest-cov
  - pip:
      #- classy<3
      - isitgr
      - velocileptors @ git+https://github.com/sfschen/velocileptors
      - baccoemu @ git+https://bitbucket.org/rangulo/baccoemu.git@master
      - amemu @ https://test.pypi.org/simple/ amemu==0.0.18
