name: test  # default testing environment name from conda-incubator
dependencies:
  - python=3.8
  - pip
  - cmake
  - gsl
  - swig
  - pyyaml
  - numpy
  - scipy
  - camb=1.3.6
  - isitgr
  - fast-pt
  - pytest
  - pytest-cov
  - pip:
      - classy=3.2.0.1
      - baccoemu @ git+https://bitbucket.org/rangulo/baccoemu.git@master
      - velocileptors @ git+https://github.com/sfschen/velocileptors
      - aemulus_heft @ git+https://github.com/AemulusProject/aemulus_heft
