name: test  # default testing environment name from conda-incubator
dependencies:
  - python=3.9
  - pip
  - cmake
  - gsl
  - swig
  - pyyaml
  - numpy
  - scipy=1.11.0
  - camb=1.3.6
  - isitgr
  - fast-pt
  - pytest
  - pytest-cov
  - pip:
      - classy<3
      - velocileptors @ git+https://github.com/sfschen/velocileptors
      - baccoemu @ git+https://bitbucket.org/rangulo/baccoemu.git@master
