name: test  # default testing environment name from conda-incubator
dependencies:
  - python=3.8
  - pip
  - cmake
  - gsl
  - swig
  - pyyaml
  - numpy
  - scipy
  - cython
  - camb=1.3.6
  - isitgr
  - fast-pt
  - pytest
  - pytest-cov
  - pip:
      - classy<3
      - baccoemu @ git+https://bitbucket.org/rangulo/baccoemu.git@master

